name: loco_2012
description: A new Flutter project.

publish_to: 'none' # This indicates the package is not published to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.4
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.2.0
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.20.0
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.0.0
  get_it: ^7.6.7
  json_annotation: ^4.8.1
  url_launcher: ^6.1.7
  image_picker: ^1.0.7
  firebase_storage: ^11.7.7
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  freezed: ^2.3.0
  auto_route_generator: ^7.3.2
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
